use sphinx < 6.0
otherwise we get (with sphinx 7):

    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'sphinx.setup_command'
Error: Process completed with exit code 1.

and also (with sphinx 6):

Exception occurred:
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/sphinx/domains/python.py", line 547, in handle_signature
    raise TypeError(
TypeError: Python directive method get_signature_prefix() must return a list of nodes. Return value was 'coroutine '.
The full traceback has been saved in /tmp/sphinx-err-t267nzfq.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
reading sources... [ 50%] fuse_api